[build]
  # base = "public/"
  publish = "public/"
  command = 'echo "export default { previous: \"$CACHED_COMMIT_REF\", current: \"$COMMIT_REF\" }" > ./public/commits.js'

[dev]
  port = 8888
  publish = "public/"
  autoLaunch = true

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=15552001; includeSubDomains; preload; redirectHttpToHttps=true"
