[build]
  # base = "public/"
  publish = "public/"
  command = "echo 'export default { prev: \"$CACHED_COMMIT_REF\", curr: \"$COMMIT_REF\" }' > ./public/hash.js"

[dev]
  port = 8888
  publish = "public/"
  autoLaunch = true

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=15552001; includeSubDomains; preload; redirectHttpToHttps=true"
